DATABASE:
  HOST: "127.0.0.1"
  PORT: 3306
  DATABASE: "PlayerHeadHunt"
  USERNAME: "root"
  PASSWORD: "root"
REGION:
  UPPERREGION:
    X: -54
    Y: 255 # Do not change this, this expands vertically.
    Z: 48
  LOWERREGION:
    X: -33
    Y: 0 # Do not change this, this expands vertically.
    Z: 4
FEATURE:
  MILESTONEHAT: TRUE
  MILESTONEMESSAGE: TRUE
HEAD:
  HEADTOTAL:
  HEADBLOCK: PLAYER_HEAD
  RESPAWNTIMER: 1200 # Default is 1200 (1 minute)
  SKINSMAX: 9
  SKINS:
    0: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGM1MGFlZTg4MDEzZThmYWY0MjdlMTlmM2I4OTgyOGI4NmJiZjAzZGQyZjE3YzRjNzYwZDFkZGUyMmRlMyJ9fX0="
    1: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzc2NTk1ZWZmY2M1NjI3ZTg1YjE0YzljODgyNDY3MWI1ZWMyOTY1NjU5YzhjNDE3ODQ5YTY2Nzg3OGZhNDkwIn19fQ=="
    2: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTk5YzRlYTA0ZDhmZGUxM2QxMjRjYjJmNjc3M2I3MWY3YTQ3MjllZmY4NWE5NmNjMTU1ZjUyY2FkZjhlYzVlIn19fQ=="
    3: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTIxM2Q2N2JjNzJmMzA4NTMzN2FiYzliZDgxMzczZWQ1ODk0MzVhYzJmMGU4MjliZWQ3YjMwNDBlZmI1NWEifX19"
    4: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWFiNzY1NzkxZmYzMTRjMjVmNGIwZGY4ZTEyODAxMzYwZWQ1YzhjMzNhZWYwY2U1OTViZDA0Mjk3ZTQ3OWViIn19fQ=="
    5: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjM1M2M3OTRmZjY4MWM4YjM1NmE0ZDFmNmQ3NGQyYTUxYzFhNGZlYzUxNzY3ODI3OWYyZTNmMmFlM2IwOWZmNyJ9fX0="
    6: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjUwOTM3YjIxNTlmMGNlZWU0ZmFjZGQ0YWJmMzU4M2FjNTVkMjQ4NGNkMjUzNDc2MjE1MzU0ZDNkN2ZlNDUifX19"
    7: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWUyMmE0ZTM5NTM3YTA0OWVhZWQ4NDcyZmY3NTAwZDRlZmE0ZmQ0NGVhOGNjNjQwMjQxNTk5MmUyZTc1ZGQxIn19fQ=="
    8: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGUzYmE1NGU0NmY0ZmNkOTI4MWVjNTkyYTVjODE3OTAxY2UzZjgxMTE4NWY3N2E5MzhjZjBjNjMzNDZlMGU2MiJ9fX0="
    9: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWMwZDA0NDNhZGQ0OTA0N2YzNDg2NDRhYjJlNTYzNjE3ZTc5ZjI1N2I3MmY4NzM4N2UwNGRkZDZiMzAxODdmOSJ9fX0="
SOUND:
  HEADFOUND: "BLOCK_NOTE_BLOCK_SNARE"
  HEADALREADYFOUND: "BLOCK_NOTE_BLOCK_BASS"
  MINORCOLLECTIONMILESTONE: "ENTITY_PLAYER_LEVELUP"
  MAJORCOLLECTIONMILESTONE: "UI_TOAST_CHALLENGE_COMPLETE"
MILESTONES:
  MINOR:
    - 16
    - 32
    - 64
    - 96
    - 160
    - 192
    - 224
  MAJOR:
    - 128
    - 256
  # These need to match up 1 to 1 with a milestone above
  LEATHERHELMET: 16
  CHAINMAILHELMET: 32
  IRONHELMET: 64
  GOLDENHELMET: 128
  DIAMONDHELMET: 192
  NETHERITEHELMET: 256 # Should equal the head count for maximum results.
LANG:
  DATABASE:
    CONNECTIONERROR: "&cA database error has occurred, please contact an Administrator."
    CONNECTIONSUCCESS: "&aDatabase connected successfully."
  COMMAND:
    NOTAPLAYER: "&cYou must be a player to run this command."
    INSUFFICENTPERMISSIONS: "&cYou do not have permission to use this command."
    COMMANDINCOMPLETE: "&cThis command is incomplete, please refer to the command guide for reference."
  HEAD:
    HEADFOUND: "&aYou have found an egg (%FOUNDHEADS%/%NUMBEROFHEADS%). %ALREADYFOUNDHEADS%."
    HEADALREADYFOUND: "&eYou have already found this egg, %ALREADYFOUNDHEADS%."
    FIRSTFINDER: "You are the first to find this egg"
    FIRSTFINDERSTILL: "You are the only person to find this egg"
    NOTFIRSTFINDERSINGLE: "%OTHERPLAYERSFOUNDHEAD% other player has found this egg"
    NOTFIRSTFINDERMULTIPLE: "%OTHERPLAYERSFOUNDHEAD% other players have found this egg"
    FIRSTHEADFOUND: "&e&l%PLAYER% &5has found their first egg!"
    LASTHEADFOUND: "&e&l%PLAYER% &5has found all &e&l%NUMBEROFHEADS% &r&5eggs!"
    HEADCOUNT: "&eYou have found &l&6%FOUNDHEADS%/%NUMBEROFHEADS% &r&eheads."
    # Use %PLAYER% to display players name, use %NUMBEROFHEADS% to display number of eggs.
    HEADCOLLECTIONMILESTONEREACHED: "&e&l%PLAYER% &5has collected &e&l%NUMBEROFHEADS% &r&5eggs!"
  LEADERBOARD:
    # You can change the length of the header to change where the "centre" is for
    # the rest of the leaderboard. Keep the line below for reference:
    # Longest header possible: "&l============================================="
    HEADER: "&l============================================="
    NOHEADS: "&lNo one has found any heads."
    FIRSTCOLOUR: "&e"
    SECONDCOLOUR: "&7"
    THIRDCOLOUR: "&6"
    FORMAT: "%COLOUR%&l%RANKING%&r&f &7-&r %PLAYER% &7- %NUMBEROFHEADS%"